language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.6
  - SYMFONY_VERSION=origin/master

before_script: 
  - php vendor/vendors.php
  - php app/console doctrine:fixture:load -e test

script: 
  - php app/console behat -e test @QaQuestionBundle

# notifications:
#   email:
#     - email@email.com